# config/config.yaml
# HERE WE STORE ALL SORTS OF CONFIGURATIONS USED FOR THE BUILD
responsive_image_widths:
  small: 320 # Mobile phones (portrait)
  medium: 640 # Tablets (portrait) & phones (landscape)
  large: 960 # Tablets (landscape) & small laptops
  xlarge: 1280 # Laptops & desktops

max_image_size: 500 #kb
